name: reviewdog
on: [pull_request, push]
jobs:
    check_spell:
        name: Check spell and language
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: reviewdog/action-languagetool@v1
              with:
                  reporter: github-pr-review
                  level: info
                  language: pt-BR
